In [95]:
import numpy as np
import pandas as pd

# ============================================================================
# NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS
# ============================================================================

print("=" * 60)
print("NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS")
print("=" * 60)

# Create retail data: 10 rows × 5 columns
# Columns: Product_ID, Price, Quantity_Sold, Customer_Rating, Days_in_Stock
retail_data = np.array([
    [1001, 29.99, 45, 4.2, 15],
    [1002, 49.99, 32, 4.5, 8],
    [1003, 19.99, 78, 3.8, 22],
    [1004, 89.99, 12, 4.7, 5],
    [1005, 15.99, 95, 4.0, 18],
    [1006, 69.99, 28, 4.3, 12],
    [1007, 39.99, 56, 3.9, 20],
    [1008, 79.99, 18, 4.6, 7],
    [1009, 25.99, 67, 4.1, 16],
    [1010, 59.99, 34, 4.4, 10]
])

print("\nORIGINAL RETAIL DATA:")
print(retail_data)
print(f"\nData shape: {retail_data.shape}")
print(f"Data type: {retail_data.dtype}")



NUMPY ASSIGNMENT: RETAIL DATA ANALYSIS

ORIGINAL RETAIL DATA:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Data shape: (10, 5)
Data type: float64


In [96]:
# ============================================================================
# QUESTION 1: ARRAY CREATION AND MANIPULATION
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 1: ARRAY CREATION AND MANIPULATION")
print("=" * 60)





QUESTION 1: ARRAY CREATION AND MANIPULATION


In [97]:
print("\nQ1.1: Create a 3x3 identity matrix using np.eye()")
print("Answer:")
identity_matrix = np.eye(3)
print(identity_matrix)



Q1.1: Create a 3x3 identity matrix using np.eye()
Answer:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
print("\nQ1.2: Create an array of 10 zeros using np.zeros()")
print("Answer:")
zeros_array = np.zeros(10)
print(zeros_array)


Q1.2: Create an array of 10 zeros using np.zeros()
Answer:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [99]:
print("\nQ1.3: Create an array of 5 ones using np.ones()")
print("Answer:")
ones_array = np.ones(5)
print(ones_array)


Q1.3: Create an array of 5 ones using np.ones()
Answer:
[1. 1. 1. 1. 1.]


In [100]:
print("\nQ1.4: Create an array with values from 0 to 9 using np.arange()")
print("Answer:")
range_array = np.arange(10)
print(range_array)


Q1.4: Create an array with values from 0 to 9 using np.arange()
Answer:
[0 1 2 3 4 5 6 7 8 9]


In [101]:
print("\nQ1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()")
print("Answer:")
linspace_array = np.linspace(0, 10,4)
print(linspace_array)


Q1.5: Create an array with 6 evenly spaced values from 0 to 10 using np.linspace()
Answer:
[ 0.          3.33333333  6.66666667 10.        ]


In [102]:
# ============================================================================
# QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION")
print("=" * 60)

print("\nQ2.1: What is the shape of the retail_data array?")
print("Answer:")
print(f"Shape: {retail_data.shape}")

print("\nQ2.2: What is the data type of the retail_data array?")
print("Answer:")
print(f"Data type: {retail_data.dtype}")

print("\nQ2.3: What is the size (total number of elements) of the retail_data array?")
print("Answer:")
print(f"Size: {retail_data.size}")

print("\nQ2.4: What is the number of dimensions of the retail_data array?")
print("Answer:")
print(f"Dimensions: {retail_data.ndim}")

print("\nQ2.5: What is the memory size of the retail_data array in bytes?")
print("Answer:")
print(f"Memory size: {retail_data.nbytes} bytes")




QUESTION 2: ARRAY ATTRIBUTES AND INFORMATION

Q2.1: What is the shape of the retail_data array?
Answer:
Shape: (10, 5)

Q2.2: What is the data type of the retail_data array?
Answer:
Data type: float64

Q2.3: What is the size (total number of elements) of the retail_data array?
Answer:
Size: 50

Q2.4: What is the number of dimensions of the retail_data array?
Answer:
Dimensions: 2

Q2.5: What is the memory size of the retail_data array in bytes?
Answer:
Memory size: 400 bytes


In [103]:
# ============================================================================
# QUESTION 3: INDEXING AND SLICING
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 3: INDEXING AND SLICING")
print("=" * 60)

print("\nQ3.1: Extract the first row of retail_data")
print("Answer:")
first_row = retail_data[0]
print(first_row)

print("\nQ3.2: Extract the last row of retail_data")
print("Answer:")
last_row = retail_data[-1]
print(last_row)

print("\nQ3.3: Extract the Price column (column index 1)")
print("Answer:")
price_column = retail_data[: ,1]
print(price_column)

print("\nQ3.4: Extract the first 3 rows and first 2 columns")
print("Answer:")
subset = retail_data[:3, :2]
print(subset)

print("\nQ3.5: Extract rows 2 to 5 (inclusive)")
print("Answer:")
rows_2_to_5 = retail_data[2:6]
print(rows_2_to_5)




QUESTION 3: INDEXING AND SLICING

Q3.1: Extract the first row of retail_data
Answer:
[1001.     29.99   45.      4.2    15.  ]

Q3.2: Extract the last row of retail_data
Answer:
[1010.     59.99   34.      4.4    10.  ]

Q3.3: Extract the Price column (column index 1)
Answer:
[29.99 49.99 19.99 89.99 15.99 69.99 39.99 79.99 25.99 59.99]

Q3.4: Extract the first 3 rows and first 2 columns
Answer:
[[1001.     29.99]
 [1002.     49.99]
 [1003.     19.99]]

Q3.5: Extract rows 2 to 5 (inclusive)
Answer:
[[1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]]


In [104]:
# ============================================================================
# QUESTION 4: MATHEMATICAL OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 4: MATHEMATICAL OPERATIONS")
print("=" * 60)

print("\nQ4.1: Calculate the sum of all prices")
print("Answer:")
total_price = np.sum(retail_data[:, 1])
print(f"Total price: ${total_price:.2f}")

print("\nQ4.2: Calculate the mean price")
print("Answer:")
mean_price = np.mean(retail_data[:, 1])
print(f"Mean price: ${mean_price:.2f}")

print("\nQ4.3: Calculate the standard deviation of prices")
print("Answer:")
std_price = np.std(retail_data[:, 1])
print(f"Standard deviation of prices: ${std_price:.2f}")

print("\nQ4.4: Calculate the variance of prices")
print("Answer:")
var_price = np.var(retail_data[:, 1])
print(f"Variance of prices: ${var_price:.2f}")

print("\nQ4.5: Calculate the median price")
print("Answer:")
median_price = np.median(retail_data[:, 1])
print(f"Median price: ${median_price:.2f}")


QUESTION 4: MATHEMATICAL OPERATIONS

Q4.1: Calculate the sum of all prices
Answer:
Total price: $481.90

Q4.2: Calculate the mean price
Answer:
Mean price: $48.19

Q4.3: Calculate the standard deviation of prices
Answer:
Standard deviation of prices: $24.70

Q4.4: Calculate the variance of prices
Answer:
Variance of prices: $609.96

Q4.5: Calculate the median price
Answer:
Median price: $44.99


In [105]:
# ============================================================================
# QUESTION 5: STATISTICAL FUNCTIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 5: STATISTICAL FUNCTIONS")
print("=" * 60)

print("\nQ5.1: Find the minimum and maximum prices")
print("Answer:")
min_price = np.min(retail_data[:, 1])
max_price = np.max(retail_data[:, 1])
print(f"Minimum price: ${min_price:.2f}")
print(f"Maximum price: ${max_price:.2f}")

print("\nQ5.2: Find the minimum and maximum quantities sold")
print("Answer:")
min_qty = np.min(retail_data[:, 2])
max_qty = np.max(retail_data[:, 2])
print(f"Minimum quantity: {min_qty}")
print(f"Maximum quantity: {max_qty}")

print("\nQ5.3: Calculate the percentile values for prices (25th, 50th, 75th)")
print("Answer:")
percentiles = np.percentile(retail_data[:, 1], [25, 50, 75])
print(f"25th percentile: ${percentiles[0]:.2f}")
print(f"50th percentile: ${percentiles[1]:.2f}")
print(f"75th percentile: ${percentiles[2]:.2f}")

print("\nQ5.4: Calculate the correlation between prices and quantities sold")
print("Answer:")
correlation = np.corrcoef(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Correlation: {correlation:.4f}")

print("\nQ5.5: Calculate the covariance between prices and quantities sold")
print("Answer:")
covariance = np.cov(retail_data[:, 1], retail_data[:, 2])[0, 1]
print(f"Covariance: {covariance:.4f}")



QUESTION 5: STATISTICAL FUNCTIONS

Q5.1: Find the minimum and maximum prices
Answer:
Minimum price: $15.99
Maximum price: $89.99

Q5.2: Find the minimum and maximum quantities sold
Answer:
Minimum quantity: 12.0
Maximum quantity: 95.0

Q5.3: Calculate the percentile values for prices (25th, 50th, 75th)
Answer:
25th percentile: $26.99
50th percentile: $44.99
75th percentile: $67.49

Q5.4: Calculate the correlation between prices and quantities sold
Answer:
Correlation: -0.9291

Q5.5: Calculate the covariance between prices and quantities sold
Answer:
Covariance: -653.4444


In [106]:
# ============================================================================
# QUESTION 6: ARRAY RESHAPING AND MANIPULATION
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 6: ARRAY RESHAPING AND MANIPULATION")
print("=" * 60)

print("\nQ6.1: Reshape the retail_data to 5 rows × 10 columns")
print("Answer:")
reshaped_5x10 = retail_data.reshape(5, 10)
print(reshaped_5x10)

print("\nQ6.2: Flatten the retail_data to a 1D array")
print("Answer:")
flattened = retail_data.flatten()
print(flattened)

print("\nQ6.3: Transpose the retail_data")
print("Answer:")
transposed = retail_data.T
print(transposed)

print("\nQ6.4: Split the retail_data into 2 equal parts vertically")
print("Answer:")
split_horizontally = np.vsplit(retail_data, 2)
print("First part:")
print(split_horizontally[0])
print("\nSecond part:")
print(split_horizontally[1])


QUESTION 6: ARRAY RESHAPING AND MANIPULATION

Q6.1: Reshape the retail_data to 5 rows × 10 columns
Answer:
[[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
     8.  ]
 [1003.     19.99   78.      3.8    22.   1004.     89.99   12.      4.7
     5.  ]
 [1005.     15.99   95.      4.     18.   1006.     69.99   28.      4.3
    12.  ]
 [1007.     39.99   56.      3.9    20.   1008.     79.99   18.      4.6
     7.  ]
 [1009.     25.99   67.      4.1    16.   1010.     59.99   34.      4.4
    10.  ]]

Q6.2: Flatten the retail_data to a 1D array
Answer:
[1001.     29.99   45.      4.2    15.   1002.     49.99   32.      4.5
    8.   1003.     19.99   78.      3.8    22.   1004.     89.99   12.
    4.7     5.   1005.     15.99   95.      4.     18.   1006.     69.99
   28.      4.3    12.   1007.     39.99   56.      3.9    20.   1008.
   79.99   18.      4.6     7.   1009.     25.99   67.      4.1    16.
 1010.     59.99   34.      4.4    10.  ]

Q6.3: Transpose t

In [107]:
print("\nQ6.5: Split the retail_data into 2 equal parts horizontally")
print("Answer:")

split_vertically = np.hsplit(retail_data, 5)

print("First part:")
print(split_vertically[0])

print("\nSecond part:")
print(split_vertically[1])

print("\nThird part:")
print(split_vertically[2])


Q6.5: Split the retail_data into 2 equal parts horizontally
Answer:
First part:
[[1001.]
 [1002.]
 [1003.]
 [1004.]
 [1005.]
 [1006.]
 [1007.]
 [1008.]
 [1009.]
 [1010.]]

Second part:
[[29.99]
 [49.99]
 [19.99]
 [89.99]
 [15.99]
 [69.99]
 [39.99]
 [79.99]
 [25.99]
 [59.99]]

Third part:
[[45.]
 [32.]
 [78.]
 [12.]
 [95.]
 [28.]
 [56.]
 [18.]
 [67.]
 [34.]]


In [108]:
# ============================================================================
# QUESTION 7: LOGICAL OPERATIONS AND FILTERING
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 7: LOGICAL OPERATIONS AND FILTERING")
print("=" * 60)

print("\nQ7.1: Find products with price greater than $50")
print("Answer:")
expensive_products = retail_data[retail_data[:, 1] > 50]
print(expensive_products)

print("\nQ7.2: Find products with customer rating greater than 4.0")
print("Answer:")
high_rated = retail_data[retail_data[:, 3] > 4.0]
print(high_rated)

print("\nQ7.3: Find products with quantity sold greater than 50 AND price less than $40")
print("Answer:")
popular_affordable = retail_data[(retail_data[:, 2] > 50) & (retail_data[:, 1] < 40)]
print(popular_affordable)

print("\nQ7.4: Count how many products have price between $20 and $60")
print("Answer:")
price_range_count = np.sum((retail_data[:, 1] >= 20) & (retail_data[:, 1] <= 60))
print(f"Products in $20-$60 range: {price_range_count}")

print("\nQ7.5: Find the index of the product with the highest rating")
print("Answer:")
highest_rating_idx = np.argmax(retail_data[:, 3])
print(f"Index: {highest_rating_idx}, Product ID: {retail_data[highest_rating_idx, 0]}")



QUESTION 7: LOGICAL OPERATIONS AND FILTERING

Q7.1: Find products with price greater than $50
Answer:
[[1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Q7.2: Find products with customer rating greater than 4.0
Answer:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Q7.3: Find products with quantity sold greater than 50 AND price less than $40
Answer:
[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]

Q7.4: Count how many products have price between $20 and $60
Answer:
Products in $20-$60 rang

In [109]:
# ============================================================================
# QUESTION 8: SORTING AND SEARCHING
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 8: SORTING AND SEARCHING")
print("=" * 60)

print("\nQ8.1: Sort the retail_data by price (ascending)")
print("Answer:")
sorted_by_price = retail_data[retail_data[:, 1].argsort()]
print(sorted_by_price)

print("\nQ8.2: Sort the retail_data by quantity sold (descending)")
print("Answer:")
sorted_by_qty_desc = retail_data[(-retail_data[:, 2]).argsort()]
print(sorted_by_qty_desc)

print("\nQ8.3: Find the indices that would sort the array by customer rating")
print("Answer:")
rating_sort_indices = np.argsort(retail_data[:, 3])
print(rating_sort_indices)

print("\nQ8.4: Find the product with the second highest price")
print("Answer:")
second_highest_price_idx = np.argsort(retail_data[:, 1])[-2]
second_highest_product = retail_data[second_highest_price_idx]
print(f"Product ID: {second_highest_product[0]}, Price: ${second_highest_product[1]:.2f}")

print("\nQ8.5: Find the product with the lowest quantity sold")
print("Answer:")
lowest_qty_idx = np.argmin(retail_data[:, 2])
lowest_qty_product = retail_data[lowest_qty_idx]
print(f"Product ID: {lowest_qty_product[0]}, Quantity: {lowest_qty_product[2]}")




QUESTION 8: SORTING AND SEARCHING

Q8.1: Sort the retail_data by price (ascending)
Answer:
[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12.      4.7     5.  ]]

Q8.2: Sort the retail_data by quantity sold (descending)
Answer:
[[1005.     15.99   95.      4.     18.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1004.     89.99   12. 

In [110]:
# ============================================================================
# QUESTION 9: MATHEMATICAL FUNCTIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 9: MATHEMATICAL FUNCTIONS")
print("=" * 60)

print("\nQ9.1: Calculate the absolute values of all elements")
print("Answer:")
absolute_values = np.abs(retail_data)
print(absolute_values)

print("\nQ9.2: Calculate the square root of all prices")
print("Answer:")
sqrt_prices = np.sqrt(retail_data[:, 1])
print(sqrt_prices)

print("\nQ9.3: Calculate the square of all quantities sold")
print("Answer:")
squared_qty = np.square(retail_data[:, 2])
print(squared_qty)

print("\nQ9.4: Calculate the exponential of all customer ratings")
print("Answer:")
exp_ratings = np.exp(retail_data[:, 3]) # means e^4th row values and e =2.718
print(exp_ratings)

print("\nQ9.5: Calculate the natural logarithm of all prices")
print("Answer:")
log_prices = np.log(retail_data[:, 1])
print(log_prices)




QUESTION 9: MATHEMATICAL FUNCTIONS

Q9.1: Calculate the absolute values of all elements
Answer:
[[1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1004.     89.99   12.      4.7     5.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]]

Q9.2: Calculate the square root of all prices
Answer:
[5.47631263 7.07036067 4.47101778 9.48630592 3.9987498  8.36600263
 6.3237647  8.94371288 5.09803884 7.74532117]

Q9.3: Calculate the square of all quantities sold
Answer:
[2025. 1024. 6084.  144. 9025.  784. 3136.  324. 4489. 1156.]

Q9.4: Calculate the exponential of all customer ratings
Answer:
[ 66.68633104  90.0171313   44.70118449 109.94717245  54.59815003
  73.6997937   49.40244911  99.48431564  60.3402876 

In [111]:
# ============================================================================
# QUESTION 10: ADVANCED OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 10: ADVANCED OPERATIONS")
print("=" * 60)

print("\nQ10.1: Calculate the cumulative sum of prices")
print("Answer:")
cumsum_prices = np.cumsum(retail_data[:, 3])
print(cumsum_prices)

print("\nQ10.2: Calculate the cumulative product of quantities sold")
print("Answer:")
cumprod_qty = np.cumprod(retail_data[:, 2])
print(cumprod_qty)

print("\nQ10.3: Calculate the difference between consecutive prices")
print("Answer:")
diff_prices = np.diff(retail_data[:, 2])
print(diff_prices)

print("\nQ10.4: Calculate the gradient of prices")
print("Answer:")
gradient_prices = np.gradient(retail_data[:, 1])
print(gradient_prices)

print("\nQ10.5: Calculate the histogram of prices with 5 bins")
print("Answer:")
hist_prices, bin_edges = np.histogram(retail_data[:, 1], bins=5)
print(f"Histogram counts: {hist_prices}")
print(f"Bin edges: {bin_edges}")



QUESTION 10: ADVANCED OPERATIONS

Q10.1: Calculate the cumulative sum of prices
Answer:
[ 4.2  8.7 12.5 17.2 21.2 25.5 29.4 34.  38.1 42.5]

Q10.2: Calculate the cumulative product of quantities sold
Answer:
[4.50000000e+01 1.44000000e+03 1.12320000e+05 1.34784000e+06
 1.28044800e+08 3.58525440e+09 2.00774246e+11 3.61393644e+12
 2.42133741e+14 8.23254720e+15]

Q10.3: Calculate the difference between consecutive prices
Answer:
[-13.  46. -66.  83. -67.  28. -38.  49. -33.]

Q10.4: Calculate the gradient of prices
Answer:
[ 20.  -5.  20.  -2. -10.  12.   5.  -7. -10.  34.]

Q10.5: Calculate the histogram of prices with 5 bins
Answer:
Histogram counts: [4 1 2 1 2]
Bin edges: [15.99 30.79 45.59 60.39 75.19 89.99]


In [112]:
print("\nQ11.2: Generate 5 random floats between 1 and 5")
print("Answer:")

random_floats = np.random.uniform(1,2, 5)
print(random_floats)


Q11.2: Generate 5 random floats between 1 and 5
Answer:
[1.43532239 1.4203678  1.33033482 1.20464863 1.61927097]


In [113]:
# ============================================================================
# QUESTION 11: RANDOM NUMBERS AND SIMULATION
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 11: RANDOM NUMBERS AND SIMULATION")
print("=" * 60)

print("\nQ11.1: Generate 5 random integers between 1 and 100")
print("Answer:")
random_ints = np.random.randint(1, 101, 5)
print(random_ints)

print("\nQ11.2: Generate 5 random floats between 0 and 1")
print("Answer:")
random_floats = np.random.random(5)
print(random_floats)

print("\nQ11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)")
print("Answer:")
normal_random = np.random.normal(0, 1, 5)
print(normal_random)

print("\nQ11.4: Shuffle the retail_data rows randomly")
print("Answer:")
shuffled_data = retail_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)

print("\nQ11.5: Set random seed to 42 and generate 3 random numbers")
print("Answer:")
np.random.seed(2)
seeded_random = np.random.random(3)
print(seeded_random)




QUESTION 11: RANDOM NUMBERS AND SIMULATION

Q11.1: Generate 5 random integers between 1 and 100
Answer:
[64 32 91 21 38]

Q11.2: Generate 5 random floats between 0 and 1
Answer:
[0.68302599 0.49856117 0.58679698 0.71975423 0.25849809]

Q11.3: Generate 5 random numbers from normal distribution (mean=0, std=1)
Answer:
[-2.24587483  1.11957525 -1.054368   -1.0088915  -0.06752199]

Q11.4: Shuffle the retail_data rows randomly
Answer:
[[1004.     89.99   12.      4.7     5.  ]
 [1008.     79.99   18.      4.6     7.  ]
 [1006.     69.99   28.      4.3    12.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1001.     29.99   45.      4.2    15.  ]
 [1002.     49.99   32.      4.5     8.  ]
 [1009.     25.99   67.      4.1    16.  ]
 [1010.     59.99   34.      4.4    10.  ]
 [1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]]

Q11.5: Set random seed to 42 and generate 3 random numbers
Answer:
[0.4359949  0.02592623 0.54966248]


In [114]:
print("\nQ12.2: Calculate the cross product of first two rows")
print("Answer:")
cross_product = np.cross(retail_data[0, :2], retail_data[1, :2])
print(cross_product)


Q12.2: Calculate the cross product of first two rows
Answer:
19990.010000000006


C:\Users\LAKSHMAN\AppData\Local\Temp\ipykernel_10628\512868678.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cross_product = np.cross(retail_data[0, :2], retail_data[1, :2])


In [115]:
# ============================================================================
# QUESTION 12: LINEAR ALGEBRA OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 12: LINEAR ALGEBRA OPERATIONS")
print("=" * 60)

print("\nQ12.1: Calculate the dot product of price and quantity columns")
print("Answer:")
dot_product = np.dot(retail_data[:, 1], retail_data[:, 2])
print(f"Dot product: {dot_product:.2f}")

print("\nQ12.2: Calculate the cross product of first two rows")
print("Answer:")
cross_product = np.cross(retail_data[0, :3], retail_data[1, :3])
print(cross_product)

print("\nQ12.3: Calculate the norm (magnitude) of the price column")
print("Answer:")
price_norm = np.linalg.norm(retail_data[:, 1])
print(f"Price norm: {price_norm:.2f}")

print("\nQ12.4: Create a 2x2 matrix and calculate its determinant")
print("Answer:")
matrix_2x2 = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(matrix_2x2)
print(f"Matrix:\n{matrix_2x2}")
print(f"Determinant: {determinant}")

print("\nQ12.5: Calculate the inverse of the 2x2 matrix")
print("Answer:")
inverse_matrix = np.linalg.inv(matrix_2x2)
print(f"Inverse matrix:\n{inverse_matrix}")





QUESTION 12: LINEAR ALGEBRA OPERATIONS

Q12.1: Calculate the dot product of price and quantity columns
Answer:
Dot product: 16527.35

Q12.2: Calculate the cross product of first two rows
Answer:
[-1289.87 13058.   19990.01]

Q12.3: Calculate the norm (magnitude) of the price column
Answer:
Price norm: 171.24

Q12.4: Create a 2x2 matrix and calculate its determinant
Answer:
Matrix:
[[2 3]
 [1 4]]
Determinant: 5.000000000000001

Q12.5: Calculate the inverse of the 2x2 matrix
Answer:
Inverse matrix:
[[ 0.8 -0.6]
 [-0.2  0.4]]


In [ ]:
# ============================================================================
# QUESTION 13: STRING OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 13: STRING OPERATIONS")
print("=" * 60)

print("\nQ13.1: Convert all product IDs to strings")
print("Answer:")
product_ids_str = retail_data[:, 0].astype(str)
print(product_ids_str)

print("\nQ13.2: Check if any product ID contains '100'")
print("Answer:")
contains_100 = np.char.find(product_ids_str, '100') >= 0
print(contains_100)

print("\nQ13.3: Convert all product IDs to uppercase (if they were strings)")
print("Answer:")
# Since they're numbers, we'll convert to string first
product_ids_upper = np.char.upper(product_ids_str)
print(product_ids_upper)

print("\nQ13.4: Count the length of each product ID string")
print("Answer:")
id_lengths = np.char.str_len(product_ids_str)
print(id_lengths)

print("\nQ13.5: Replace '100' with 'PROD' in product IDs")
print("Answer:")
replaced_ids = np.char.replace(product_ids_str, '100', 'PROD')
print(replaced_ids)




QUESTION 13: STRING OPERATIONS

Q13.1: Convert all product IDs to strings
Answer:
['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']

Q13.2: Check if any product ID contains '100'
Answer:
[ True  True  True  True  True  True  True  True  True False]

Q13.3: Convert all product IDs to uppercase (if they were strings)
Answer:
['1001.0' '1002.0' '1003.0' '1004.0' '1005.0' '1006.0' '1007.0' '1008.0'
 '1009.0' '1010.0']

Q13.4: Count the length of each product ID string
Answer:
[6 6 6 6 6 6 6 6 6 6]

Q13.5: Replace '100' with 'PROD' in product IDs
Answer:
['PROD1.0' 'PROD2.0' 'PROD3.0' 'PROD4.0' 'PROD5.0' 'PROD6.0' 'PROD7.0'
 'PROD8.0' 'PROD9.0' '1010.0']


In [117]:
# ============================================================================
# QUESTION 14: DATE AND TIME OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 14: DATE AND TIME OPERATIONS")
print("=" * 60)

print("\nQ14.1: Convert days in stock to hours")
print("Answer:")
days_to_hours = retail_data[:, 4] * 24
print(days_to_hours)

print("\nQ14.2: Calculate the average days in stock")
print("Answer:")
avg_days = np.mean(retail_data[:, 4])
print(f"Average days in stock: {avg_days:.1f}")

print("\nQ14.3: Find products that have been in stock for more than 15 days")
print("Answer:")
long_stock = retail_data[retail_data[:, 4] > 15]
print(long_stock)

print("\nQ14.4: Calculate the total time all products have been in stock (in days)")
print("Answer:")
total_stock_time = np.sum(retail_data[:, 4])
print(f"Total stock time: {total_stock_time} days")

print("\nQ14.5: Find the product with the shortest time in stock")
print("Answer:")
shortest_stock_idx = np.argmin(retail_data[:, 4])
shortest_stock_product = retail_data[shortest_stock_idx]
print(f"Product ID: {shortest_stock_product[0]}, Days: {shortest_stock_product[4]}")




QUESTION 14: DATE AND TIME OPERATIONS

Q14.1: Convert days in stock to hours
Answer:
[360. 192. 528. 120. 432. 288. 480. 168. 384. 240.]

Q14.2: Calculate the average days in stock
Answer:
Average days in stock: 13.3

Q14.3: Find products that have been in stock for more than 15 days
Answer:
[[1003.     19.99   78.      3.8    22.  ]
 [1005.     15.99   95.      4.     18.  ]
 [1007.     39.99   56.      3.9    20.  ]
 [1009.     25.99   67.      4.1    16.  ]]

Q14.4: Calculate the total time all products have been in stock (in days)
Answer:
Total stock time: 133.0 days

Q14.5: Find the product with the shortest time in stock
Answer:
Product ID: 1004.0, Days: 5.0


In [132]:
def f(x):
    return x**2
hli = np.vectorize(f)
hli

In [ ]:
# ============================================================================
# QUESTION 15: ADVANCED ARRAY OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 15: ADVANCED ARRAY OPERATIONS")
print("=" * 60)

print("\nQ15.1: Apply a function to square all prices")
print("Answer:")
def square_price(x):
    return x ** 2

squared_prices = np.vectorize(square_price)(retail_data[:, 1])
print(squared_prices)

print("\nQ15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'")
print("Answer:")
price_labels = np.where(retail_data[:, 1] > 50, 'Expensive', 'Affordable')
print(price_labels)

print("\nQ15.3: Use np.select to categorize products by price ranges")
print("Answer:")
conditions = [
    (retail_data[:, 1] < 20),
    (retail_data[:, 1] >= 20) & (retail_data[:, 1] < 50),
    (retail_data[:, 1] >= 50)
]
choices = ['Budget', 'Mid-range', 'Premium']
price_categories = np.select(conditions, choices, default='Unknown')
print(price_categories) 

print("\nQ15.4: Use np.piecewise to apply different functions based on price ranges")
print("Answer:")
def low_price(x): return x * 0.9  # 10% discount
def mid_price(x): return x * 1.0  # No change
def high_price(x): return x * 1.1  # 10% markup

discounted_prices = np.piecewise(
    retail_data[:, 1],
    [retail_data[:, 1] < 20, (retail_data[:, 1] >= 20) & (retail_data[:, 1] < 50), retail_data[:, 1] >= 50],
    [low_price, mid_price, high_price]
)
print(discounted_prices)

print("\nQ15.5: Use np.apply_along_axis to calculate the sum of each row")
print("Answer:")
row_sums = np.apply_along_axis(np.sum, 1, retail_data)
print(row_sums)


QUESTION 15: ADVANCED ARRAY OPERATIONS

Q15.1: Apply a function to square all prices
Answer:
[ 899.4001 2499.0001  399.6001 8098.2001  255.6801 4898.6001 1599.2001
 6398.4001  675.4801 3598.8001]

Q15.2: Use np.where to replace prices > $50 with 'Expensive' and others with 'Affordable'
Answer:
['Affordable' 'Affordable' 'Affordable' 'Expensive' 'Affordable'
 'Expensive' 'Affordable' 'Expensive' 'Affordable' 'Expensive']

Q15.3: Use np.select to categorize products by price ranges
Answer:
['Mid-range' 'Mid-range' 'Budget' 'Premium' 'Budget' 'Premium' 'Mid-range'
 'Premium' 'Mid-range' 'Premium']

Q15.4: Use np.piecewise to apply different functions based on price ranges
Answer:
[29.99  49.99  17.991 98.989 14.391 76.989 39.99  87.989 25.99  65.989]

Q15.5: Use np.apply_along_axis to calculate the sum of each row
Answer:
[1095.19 1096.49 1126.79 1115.69 1137.99 1120.29 1126.89 1117.59 1122.09
 1118.39]


In [119]:
# ============================================================================
# QUESTION 16: ARRAY CONCATENATION AND STACKING
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 16: ARRAY CONCATENATION AND STACKING")
print("=" * 60)

print("\nQ16.1: Concatenate two arrays horizontally using np.hstack()")
print("Answer:")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstacked = np.hstack([arr1, arr2])
print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"Horizontally stacked: {hstacked}")

print("\nQ16.2: Concatenate two arrays vertically using np.vstack()")
print("Answer:")
vstacked = np.vstack([arr1, arr2])
print(f"Vertically stacked:\n{vstacked}")

print("\nQ16.3: Concatenate arrays along a specific axis using np.concatenate()")
print("Answer:")
concatenated = np.concatenate([arr1, arr2], axis=0)
print(f"Concatenated along axis 0: {concatenated}")

print("\nQ16.4: Stack arrays depth-wise using np.dstack()")
print("Answer:")
dstacked = np.dstack([arr1, arr2])
print(f"Depth-wise stacked:\n{dstacked}")

print("\nQ16.5: Create a column stack using np.column_stack()")
print("Answer:")
col_stacked = np.column_stack([arr1, arr2])
print(f"Column stacked:\n{col_stacked}")




QUESTION 16: ARRAY CONCATENATION AND STACKING

Q16.1: Concatenate two arrays horizontally using np.hstack()
Answer:
Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontally stacked: [1 2 3 4 5 6]

Q16.2: Concatenate two arrays vertically using np.vstack()
Answer:
Vertically stacked:
[[1 2 3]
 [4 5 6]]

Q16.3: Concatenate arrays along a specific axis using np.concatenate()
Answer:
Concatenated along axis 0: [1 2 3 4 5 6]

Q16.4: Stack arrays depth-wise using np.dstack()
Answer:
Depth-wise stacked:
[[[1 4]
  [2 5]
  [3 6]]]

Q16.5: Create a column stack using np.column_stack()
Answer:
Column stacked:
[[1 4]
 [2 5]
 [3 6]]


In [120]:
# ============================================================================
# QUESTION 17: ARRAY SPLITTING OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 17: ARRAY SPLITTING OPERATIONS")
print("=" * 60)

print("\nQ17.1: Split an array into 3 equal parts using np.split()")
print("Answer:")
arr_to_split = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
split_parts = np.split(arr_to_split, 3)
print(f"Original array: {arr_to_split}")
for i, part in enumerate(split_parts):
    print(f"Part {i+1}: {part}")

print("\nQ17.2: Split an array at specific indices using np.split()")
print("Answer:")
split_at_indices = np.split(arr_to_split, [3, 6])
print(f"Split at indices [3, 6]:")
for i, part in enumerate(split_at_indices):
    print(f"Part {i+1}: {part}")

print("\nQ17.3: Split an array horizontally using np.hsplit()")
print("Answer:")
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
print(f"Original 2D array:\n{arr_2d}")
for i, part in enumerate(hsplit_parts):
    print(f"Horizontal part {i+1}:\n{part}")

print("\nQ17.4: Split an array vertically using np.vsplit()")
print("Answer:")
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:")
for i, part in enumerate(vsplit_parts):
    print(f"Part {i+1}:\n{part}")

print("\nQ17.5: Split an array into equal chunks using np.array_split()")
print("Answer:")
chunks = np.array_split(arr_to_split, 4)
print(f"Split into 4 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i+1}: {chunk}")




QUESTION 17: ARRAY SPLITTING OPERATIONS

Q17.1: Split an array into 3 equal parts using np.split()
Answer:
Original array: [1 2 3 4 5 6 7 8 9]
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]

Q17.2: Split an array at specific indices using np.split()
Answer:
Split at indices [3, 6]:
Part 1: [1 2 3]
Part 2: [4 5 6]
Part 3: [7 8 9]

Q17.3: Split an array horizontally using np.hsplit()
Answer:
Original 2D array:
[[1 2 3]
 [4 5 6]]
Horizontal part 1:
[[1]
 [4]]
Horizontal part 2:
[[2]
 [5]]
Horizontal part 3:
[[3]
 [6]]

Q17.4: Split an array vertically using np.vsplit()
Answer:
Vertical parts:
Part 1:
[[1 2 3]]
Part 2:
[[4 5 6]]

Q17.5: Split an array into equal chunks using np.array_split()
Answer:
Split into 4 chunks:
Chunk 1: [1 2 3]
Chunk 2: [4 5]
Chunk 3: [6 7]
Chunk 4: [8 9]


In [121]:
# ============================================================================
# QUESTION 18: ARRAY REPETITION AND TILING
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 18: ARRAY REPETITION AND TILING")
print("=" * 60)

print("\nQ18.1: Repeat each element of an array 3 times using np.repeat()")
print("Answer:")
repeat_elements = np.repeat(arr1, 3)
print(f"Original: {arr1}")
print(f"Repeated 3 times: {repeat_elements}")

print("\nQ18.2: Repeat an entire array 2 times using np.tile()")
print("Answer:")
tiled_array = np.tile(arr1, 2)
print(f"Original: {arr1}")
print(f"Tiled 2 times: {tiled_array}")

print("\nQ18.3: Repeat a 2D array using np.tile()")
print("Answer:")
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small, (2, 3))
print(f"Original:\n{arr_2d_small}")
print(f"Tiled (2, 3):\n{tiled_2d}")

print("\nQ18.4: Create a pattern using np.tile()")
print("Answer:")
pattern = np.array([1, 0])
pattern_tiled = np.tile(pattern, 5)
print(f"Pattern: {pattern}")
print(f"Tiled 5 times: {pattern_tiled}")

print("\nQ18.5: Repeat elements with different counts using np.repeat()")
print("Answer:")
repeat_counts = [2, 1, 3]
repeated_variable = np.repeat(arr1, repeat_counts)
print(f"Original: {arr1}")
print(f"Repeat counts: {repeat_counts}")
print(f"Result: {repeated_variable}")




QUESTION 18: ARRAY REPETITION AND TILING

Q18.1: Repeat each element of an array 3 times using np.repeat()
Answer:
Original: [1 2 3]
Repeated 3 times: [1 1 1 2 2 2 3 3 3]

Q18.2: Repeat an entire array 2 times using np.tile()
Answer:
Original: [1 2 3]
Tiled 2 times: [1 2 3 1 2 3]

Q18.3: Repeat a 2D array using np.tile()
Answer:
Original:
[[1 2]
 [3 4]]
Tiled (2, 3):
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]

Q18.4: Create a pattern using np.tile()
Answer:
Pattern: [1 0]
Tiled 5 times: [1 0 1 0 1 0 1 0 1 0]

Q18.5: Repeat elements with different counts using np.repeat()
Answer:
Original: [1 2 3]
Repeat counts: [2, 1, 3]
Result: [1 1 2 3 3 3]


In [122]:
# ============================================================================
# QUESTION 19: ARRAY COMPARISON AND LOGICAL OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 19: ARRAY COMPARISON AND LOGICAL OPERATIONS")
print("=" * 60)

print("\nQ19.1: Compare two arrays for equality using np.array_equal()")
print("Answer:")
arr_a = np.array([1, 2, 3])
arr_b = np.array([1, 2, 3])
arr_c = np.array([1, 2, 4])
print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Array C: {arr_c}")
print(f"A equals B: {np.array_equal(arr_a, arr_b)}")
print(f"A equals C: {np.array_equal(arr_a, arr_c)}")

print("\nQ19.2: Check if arrays are close using np.allclose()")
print("Answer:")
arr_d = np.array([1.0, 2.0, 3.0])
arr_e = np.array([1.001, 2.001, 3.001])
print(f"Array D: {arr_d}")
print(f"Array E: {arr_e}")
print(f"Arrays are close: {np.allclose(arr_d, arr_e, atol=0.01)}")

print("\nQ19.3: Apply logical AND operation between arrays")
print("Answer:")
logical_and = np.logical_and(arr_a > 1, arr_a < 3)
print(f"Array: {arr_a}")
print(f"Logical AND (1 < x < 3): {logical_and}")

print("\nQ19.4: Apply logical OR operation between arrays")
print("Answer:")
logical_or = np.logical_or(arr_a == 1, arr_a == 3)
print(f"Array: {arr_a}")
print(f"Logical OR (x == 1 OR x == 3): {logical_or}")

print("\nQ19.5: Apply logical NOT operation to an array")
print("Answer:")
logical_not = np.logical_not(arr_a == 2)
print(f"Array: {arr_a}")
print(f"Logical NOT (x != 2): {logical_not}")




QUESTION 19: ARRAY COMPARISON AND LOGICAL OPERATIONS

Q19.1: Compare two arrays for equality using np.array_equal()
Answer:
Array A: [1 2 3]
Array B: [1 2 3]
Array C: [1 2 4]
A equals B: True
A equals C: False

Q19.2: Check if arrays are close using np.allclose()
Answer:
Array D: [1. 2. 3.]
Array E: [1.001 2.001 3.001]
Arrays are close: True

Q19.3: Apply logical AND operation between arrays
Answer:
Array: [1 2 3]
Logical AND (1 < x < 3): [False  True False]

Q19.4: Apply logical OR operation between arrays
Answer:
Array: [1 2 3]
Logical OR (x == 1 OR x == 3): [ True False  True]

Q19.5: Apply logical NOT operation to an array
Answer:
Array: [1 2 3]
Logical NOT (x != 2): [ True False  True]


In [123]:
# ============================================================================
# QUESTION 20: ARRAY SET OPERATIONS
# ============================================================================

print("\n" + "=" * 60)
print("QUESTION 20: ARRAY SET OPERATIONS")
print("=" * 60)

print("\nQ20.1: Find unique elements in an array using np.unique()")
print("Answer:")
arr_with_duplicates = np.array([1, 2, 2, 3, 3, 3, 4])
unique_elements = np.unique(arr_with_duplicates)
print(f"Original array: {arr_with_duplicates}")
print(f"Unique elements: {unique_elements}")

print("\nQ20.2: Find the intersection of two arrays using np.intersect1d()")
print("Answer:")
arr_f = np.array([1, 2, 3, 4])
arr_g = np.array([3, 4, 5, 6])
intersection = np.intersect1d(arr_f, arr_g)
print(f"Array F: {arr_f}")
print(f"Array G: {arr_g}")
print(f"Intersection: {intersection}")

print("\nQ20.3: Find the union of two arrays using np.union1d()")
print("Answer:")
union = np.union1d(arr_f, arr_g)
print(f"Union: {union}")

print("\nQ20.4: Find elements in first array but not in second using np.setdiff1d()")
print("Answer:")
set_difference = np.setdiff1d(arr_f, arr_g)
print(f"Elements in F but not in G: {set_difference}")

print("\nQ20.5: Find the symmetric difference between two arrays using np.setxor1d()")
print("Answer:")
symmetric_diff = np.setxor1d(arr_f, arr_g)
print(f"Symmetric difference: {symmetric_diff}")


QUESTION 20: ARRAY SET OPERATIONS

Q20.1: Find unique elements in an array using np.unique()
Answer:
Original array: [1 2 2 3 3 3 4]
Unique elements: [1 2 3 4]

Q20.2: Find the intersection of two arrays using np.intersect1d()
Answer:
Array F: [1 2 3 4]
Array G: [3 4 5 6]
Intersection: [3 4]

Q20.3: Find the union of two arrays using np.union1d()
Answer:
Union: [1 2 3 4 5 6]

Q20.4: Find elements in first array but not in second using np.setdiff1d()
Answer:
Elements in F but not in G: [1 2]

Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
Answer:
Symmetric difference: [1 2 5 6]
