In [66]:
import numpy as np

In [67]:
banking_data = np.array([
    [2001, 15230, 720, 35, 8],
    [2002, 8450, 680, 22, 5],
    [2003, 23000, 790, 48, 12],
    [2004, 1250, 610, 15, 2],
    [2005, 17890, 750, 40, 10],
    [2006, 5400, 660, 28, 6],
    [2007, 980, 590, 12, 1],
    [2008, 21050, 810, 55, 15],
    [2009, 6700, 700, 30, 7],
    [2010, 13400, 730, 38, 9]
])


In [68]:
# Customer_ID,Account_Balance ($),Credit_Score (300–900),Transaction_Count,Years_Active
import numpy as np
import pandas as pd

columns = ["Customer_ID", "Account_Balance", "Credit_Score", "Transaction_Count", "Years_Active"]
df = pd.DataFrame(banking_data, columns=columns)

print(df)


   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0         2001            15230           720                 35             8
1         2002             8450           680                 22             5
2         2003            23000           790                 48            12
3         2004             1250           610                 15             2
4         2005            17890           750                 40            10
5         2006             5400           660                 28             6
6         2007              980           590                 12             1
7         2008            21050           810                 55            15
8         2009             6700           700                 30             7
9         2010            13400           730                 38             9


In [69]:
banking_data[3]

array([2004, 1250,  610,   15,    2])

In [70]:
# Question 1: Array Creation and Manipulation
# Q1.1: Create a 4x4 identity matrix using np.eye()
mat = np.eye(4)
print(mat)

# Q1.2: Create an array of 8 zeros using np.zeros()
arr1 = np.zeros(8)
print(arr1)
# Q1.3: Create an array of 6 ones using np.ones()
arr1 = np.ones(6)
print(arr1)
# Q1.4: Create an array with values from 0 to 15 using np.arange()
arr1 = np.arange(0,16)
print(arr1)
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
arr1 = np.linspace(0,100,8)
print(arr1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [71]:
# Question 2: Array Attributes and Information
# Q2.1: What is the shape of the banking_data array?
shape1 = np.shape(banking_data)
print(shape1)
# Q2.2: What is the data type of the banking_data array?
data_type = banking_data.dtype
print(data_type)
# Q2.3: What is the size (total number of elements) of the banking_data array?
size1 = np.size(banking_data)
print(size1)
# Q2.4: What is the number of dimensions of the banking_data array?
dimensions = np.ndim(banking_data)
print(dimensions)
# Q2.5: What is the memory size of the banking_data array in bytes?
mem_size = banking_data.nbytes
print(mem_size)

(10, 5)
int64
50
2
400


In [72]:
# Question 3: Indexing and Slicing
# Q3.1: Extract the first row of banking_data
first_row = banking_data[0]
print(first_row)

# Q3.2: Extract the last row of banking_data
last_row = banking_data[-1]
print(last_row)

# Q3.3: Extract the Account_Balance column (column index 1)
column_no = banking_data[:,1]
print(column_no)

# Q3.4: Extract the first 4 rows and first 3 columns
extract = banking_data[:4,:3]
print(extract)

# Q3.5: Extract rows 3 to 7 (inclusive)
extract2 = banking_data[3:7]
print(extract2)

[ 2001 15230   720    35     8]
[ 2010 13400   730    38     9]
[15230  8450 23000  1250 17890  5400   980 21050  6700 13400]
[[ 2001 15230   720]
 [ 2002  8450   680]
 [ 2003 23000   790]
 [ 2004  1250   610]]
[[ 2004  1250   610    15     2]
 [ 2005 17890   750    40    10]
 [ 2006  5400   660    28     6]
 [ 2007   980   590    12     1]]


In [73]:
# Question 4: Mathematical Operations
# Q4.1: Calculate the sum of all account balances
sum1 = np.sum(banking_data[:,1])
print(sum1)

# Q4.2: Calculate the mean account balance
mean1 = np.mean(banking_data[:,1])
print(mean1)

# Q4.3: Calculate the standard deviation of account balances
std1 = np.std(banking_data[:,1])
print(std1)

# Q4.4: Calculate the variance of account balances
var = np.var(banking_data[:,1])
print(var)

# Q4.5: Calculate the median account balance
median1 = np.median(banking_data[:,1])
print(median1)


113350
11335.0
7528.7492321102045
56682065.0
10925.0


In [74]:
# Question 5: Statistical Functions
# Q5.1: Find the minimum and maximum account balances
maximum = np.max(banking_data[:,1])
print(maximum)

minimum= np.min(banking_data[:,1])
print(minimum)

# Q5.2: Find the minimum and maximum credit scores
maximum1 = np.max(banking_data[:,2])
print(maximum1)

MINIMUN1 = np.min(banking_data[:,2])
print(MINIMUN1)
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentile_value = np.percentile(banking_data[:,1] , [25,50,75])
print(percentile_value)

# Q5.4: Calculate the correlation between account balance and credit score

# Q5.5: Calculate the covariance between account balance and credit score

23000
980
810
590
[ 5725. 10925. 17225.]


In [75]:
# Question 6: Array Reshaping and Manipulation
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshape = banking_data.reshape(5,10)
print(reshape)

# Q6.2: Flatten the banking_data to a 1D array
flatten = banking_data.flatten()
print(flatten)


# Q6.3: Transpose the banking_data
transposed = banking_data.T
print(transposed)

# Q6.4: Split the banking_data into 2 equal parts vertically
vertical_split = np.vsplit(banking_data,2)
print(vertical_split)
print(vertical_split[0])
# Q6.5: Split the banking_data into 2 equal parts horizontally
horizontally_split = np.hsplit(banking_data,5)
print(horizontally_split)
print(horizontally_split[1])

[[ 2001 15230   720    35     8  2002  8450   680    22     5]
 [ 2003 23000   790    48    12  2004  1250   610    15     2]
 [ 2005 17890   750    40    10  2006  5400   660    28     6]
 [ 2007   980   590    12     1  2008 21050   810    55    15]
 [ 2009  6700   700    30     7  2010 13400   730    38     9]]
[ 2001 15230   720    35     8  2002  8450   680    22     5  2003 23000
   790    48    12  2004  1250   610    15     2  2005 17890   750    40
    10  2006  5400   660    28     6  2007   980   590    12     1  2008
 21050   810    55    15  2009  6700   700    30     7  2010 13400   730
    38     9]
[[ 2001  2002  2003  2004  2005  2006  2007  2008  2009  2010]
 [15230  8450 23000  1250 17890  5400   980 21050  6700 13400]
 [  720   680   790   610   750   660   590   810   700   730]
 [   35    22    48    15    40    28    12    55    30    38]
 [    8     5    12     2    10     6     1    15     7     9]]
[array([[ 2001, 15230,   720,    35,     8],
       [ 2002,  8

In [76]:
# Question 7: Logical Operations and Filtering
# Q7.1: Find customers with account balance greater than $10,000
greater_balance = banking_data[banking_data[:,1]>10000]
print(greater_balance)
# Q7.2: Find customers with credit score greater than 800
high_score = banking_data[banking_data[:,2]>800]
print(high_score)

# Q7.3: Find customers with transaction count greater than 30 AND credit score less than 750
transaction_count = banking_data[(banking_data[:,3] > 30) & (banking_data[:,2] < 750)]
print(transaction_count)

# Q7.4: Count how many customers have account balance between $5,000 and $15,000
no_of_customers =  banking_data[(banking_data[:,1] > 5000) & (banking_data[:,1] < 15000)]
print(len(no_of_customers))

# Q7.5: Find the index of the customer with the highest credit score
index_oF_customer = np.argmax(banking_data[:,2])
print(index_oF_customer)

[[ 2001 15230   720    35     8]
 [ 2003 23000   790    48    12]
 [ 2005 17890   750    40    10]
 [ 2008 21050   810    55    15]
 [ 2010 13400   730    38     9]]
[[ 2008 21050   810    55    15]]
[[ 2001 15230   720    35     8]
 [ 2010 13400   730    38     9]]
4
7


In [77]:
# Question 8: Sorting and Searching
# Q8.1: Sort the banking_data by account balance (ascending)
sort_acc_bal = banking_data[banking_data[:,1].argsort()]
print(sort_acc_bal)

# Q8.2: Sort the banking_data by credit score (descending)
sort_acc_bal_desc = banking_data[banking_data[:,2].argsort()[::-1]]
print(sort_acc_bal_desc) 

# Q8.3: Find the indices that would sort the array by years active
indices = np.argsort(banking_data[:,4])
print(indices)


# Q8.4: Find the customer with the second highest account balance
second_highest = np.argsort(banking_data[:,1])[-2]
print(banking_data[second_highest])


# Q8.5: Find the customer with the lowest transaction count
print()
lowest_trasaction = np.argmin(banking_data[:,3])
print(banking_data[lowest_trasaction])


[[ 2007   980   590    12     1]
 [ 2004  1250   610    15     2]
 [ 2006  5400   660    28     6]
 [ 2009  6700   700    30     7]
 [ 2002  8450   680    22     5]
 [ 2010 13400   730    38     9]
 [ 2001 15230   720    35     8]
 [ 2005 17890   750    40    10]
 [ 2008 21050   810    55    15]
 [ 2003 23000   790    48    12]]
[[ 2008 21050   810    55    15]
 [ 2003 23000   790    48    12]
 [ 2005 17890   750    40    10]
 [ 2010 13400   730    38     9]
 [ 2001 15230   720    35     8]
 [ 2009  6700   700    30     7]
 [ 2002  8450   680    22     5]
 [ 2006  5400   660    28     6]
 [ 2004  1250   610    15     2]
 [ 2007   980   590    12     1]]
[6 3 1 5 8 0 9 4 2 7]
[ 2008 21050   810    55    15]

[2007  980  590   12    1]


In [78]:
# Question 9: Mathematical Functions
# Q9.1: Calculate the absolute values of all elements
absolute_values = np.abs(banking_data)
print(absolute_values)

# Q9.2: Calculate the square root of all account balances
square_root = np.sqrt(banking_data[:,1])
print(square_root)

# Q9.3: Calculate the square of all credit scores
square = np.square(banking_data[:,2])
print(square)

# Q9.4: Calculate the exponential of all transaction counts
exponential = np.exp(banking_data[:,3])# means e^4th row values and e =2.718
print(exponential)


# Q9.5: Calculate the natural logarithm of all account balances

natural_log = np.log(banking_data[:,1])
print(natural_log)


[[ 2001 15230   720    35     8]
 [ 2002  8450   680    22     5]
 [ 2003 23000   790    48    12]
 [ 2004  1250   610    15     2]
 [ 2005 17890   750    40    10]
 [ 2006  5400   660    28     6]
 [ 2007   980   590    12     1]
 [ 2008 21050   810    55    15]
 [ 2009  6700   700    30     7]
 [ 2010 13400   730    38     9]]
[123.40988615  91.92388155 151.65750888  35.35533906 133.75350463
  73.48469228  31.30495168 145.08618129  81.85352772 115.75836903]
[518400 462400 624100 372100 562500 435600 348100 656100 490000 532900]
[1.58601345e+15 3.58491285e+09 7.01673591e+20 3.26901737e+06
 2.35385267e+17 1.44625706e+12 1.62754791e+05 7.69478527e+23
 1.06864746e+13 3.18559318e+16]
[ 9.63102245  9.04192172 10.04324949  7.13089883  9.79199718  8.59415423
  6.88755257  9.95465584  8.80986281  9.50300999]


In [79]:
# Question 10: Advanced Operations
# Q10.1: Calculate the cumulative sum of account balances
cumulative_sum = np.cumsum(banking_data[:,1])
print(cumulative_sum)


# Q10.2: Calculate the cumulative product of transaction counts
cumulative_product = np.cumprod(banking_data[:,3])
print(cumulative_product)

# Q10.3: Calculate the difference between consecutive account balances
difference = np.diff(banking_data[:,1])
print(difference)

# Q10.4: Calculate the gradient of account balances
gradient = np.gradient(banking_data[:,1])
print(gradient)

# Q10.5: Calculate the histogram of account balances with 5 bins
histogram_acc , bins_acc = np.histogram(banking_data[:,1] , bins = 5)
print(f"Histogram {histogram_acc}")
print(f"Bins {bins_acc}")
"""
Example:
Account balances: [980, 1250, 5400, 6700, 8450, 13400, 15230, 17890, 21050, 23000]
Min = 980, Max = 23000
Bin width ≈ (23000 - 980)/5 ≈ 4404
Bins are [980–6104, 6104–11228, 11228–16352, 16352–21476, 21476–26600]
bin count = [3, 2, 2, 2, 1]
"""

[ 15230  23680  46680  47930  65820  71220  72200  93250  99950 113350]
[             35             770           36960          554400
        22176000       620928000      7451136000    409812480000
  12294374400000 467186227200000]
[ -6780  14550 -21750  16640 -12490  -4420  20070 -14350   6700]
[-6780.  3885. -3600. -2555.  2075. -8455.  7825.  2860. -3825.  6700.]
Histogram [2 3 1 2 2]
Bins [  980.  5384.  9788. 14192. 18596. 23000.]


'\nExample:\nAccount balances: [980, 1250, 5400, 6700, 8450, 13400, 15230, 17890, 21050, 23000]\nMin = 980, Max = 23000\nBin width ≈ (23000 - 980)/5 ≈ 4404\nBins are [980–6104, 6104–11228, 11228–16352, 16352–21476, 21476–26600]\nbin count = [3, 2, 2, 2, 1]\n'

In [80]:
# Question 11: Random Numbers and Simulation
# Q11.1: Generate 6 random integers between 1 and 1000
random_integers = np.random.randint(1,100,6)
print(random_integers)
# Q11.2: Generate 6 random floats between 0 and 1
random_floats = np.random.random(6)
print(random_floats)
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
nrml_dist = np.random.normal(700,100,6)
print(nrml_dist)
# Q11.4: Shuffle the banking_data rows randomly
copy1 = banking_data.copy()
np.random.shuffle(copy1)
print(copy1)

# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
random_seed = np.random.random(4)
print(random_seed)


[84 58 87 98 97 48]
[0.39211752 0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
[623.05665285 757.67460214 712.65259202 569.85110255 920.74274352
 752.27424693]
[[ 2007   980   590    12     1]
 [ 2009  6700   700    30     7]
 [ 2003 23000   790    48    12]
 [ 2010 13400   730    38     9]
 [ 2006  5400   660    28     6]
 [ 2005 17890   750    40    10]
 [ 2004  1250   610    15     2]
 [ 2002  8450   680    22     5]
 [ 2008 21050   810    55    15]
 [ 2001 15230   720    35     8]]
[0.69646919 0.28613933 0.22685145 0.55131477]


In [81]:
# Question 12: Linear Algebra Operations
# Q12.1: Calculate the dot product of account balance and credit score columns
dot_product = np.dot(banking_data[:,1],banking_data[:,2])
print(dot_product)

# Q12.2: Calculate the cross product of first two rows
cross_product = np.cross(banking_data[0,:3],banking_data[1,:3])
print(cross_product)


# Q12.3: Calculate the norm (magnitude) of the account balance column
#formula = sqrt(sum(square of each element of array))  sqrt(a1^2 +a2^2 +a3^2 ......)      also known as eculidian formula
norm = np.linalg.norm(banking_data[:,1]) 
print(norm)
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix = np.array([[1,2,3],[4,5,6],[10,8,9]])
print(matrix)
derminant = np.linalg.det(matrix)
print(derminant)

# Q12.5: Calculate the inverse of the 3x3 matrix
inverse = np.linalg.inv(matrix)
print(inverse)

84726300
[  4272400     80760 -13582010]
43030.720421577884
[[ 1  2  3]
 [ 4  5  6]
 [10  8  9]]
-9.000000000000002
[[ 0.33333333 -0.66666667  0.33333333]
 [-2.66666667  2.33333333 -0.66666667]
 [ 2.         -1.33333333  0.33333333]]


In [82]:
# Question 13: String Operations
# Q13.1: Convert all customer IDs to strings
conversion = banking_data[:,0].astype(str)
print(conversion)

# Q13.2: Check if any customer ID contains '200'
checking = np.char.find(conversion,'200') >=0
print(checking)

# Q13.3: Convert all customer IDs to uppercase (if they were strings)
convert_upper = np.char.upper(conversion)
print(convert_upper)

# Q13.4: Count the length of each customer ID string
length = np.char.str_len(conversion)
print(length)

# Q13.5: Replace '200' with 'CUST' in customer IDs
replace = np.char.replace(conversion,'200','CUST')
print(replace)

replace2 = df["Customer_ID"].astype(str).str.replace("200", "CUST")
print(replace2)

['2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009' '2010']
[ True  True  True  True  True  True  True  True  True False]
['2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009' '2010']
[4 4 4 4 4 4 4 4 4 4]
['CUST1' 'CUST2' 'CUST3' 'CUST4' 'CUST5' 'CUST6' 'CUST7' 'CUST8' 'CUST9'
 '2010']
0    CUST1
1    CUST2
2    CUST3
3    CUST4
4    CUST5
5    CUST6
6    CUST7
7    CUST8
8    CUST9
9     2010
Name: Customer_ID, dtype: object


In [83]:
# Question 14: Date and Time Operations
# Q14.1: Convert years active to months
yr_to_mon = banking_data[:,4]*12
print(yr_to_mon)
# Q14.2: Calculate the average years active
avg_yr = np.mean(banking_data[:,4])
print(avg_yr)

# Q14.3: Find customers who have been active for more than 5 years
customer_more_than_5yrs = banking_data[banking_data[:,4] > 5]
print(customer_more_than_5yrs)
# Q14.4: Calculate the total time all customers have been active (in years)
total_time = np.sum(banking_data[:,4])
print(total_time)
# Q14.5: Find the customer with the shortest time active
shortest = banking_data[np.argmin(banking_data[:,4])]
print(shortest)


[ 96  60 144  24 120  72  12 180  84 108]
7.5
[[ 2001 15230   720    35     8]
 [ 2003 23000   790    48    12]
 [ 2005 17890   750    40    10]
 [ 2006  5400   660    28     6]
 [ 2008 21050   810    55    15]
 [ 2009  6700   700    30     7]
 [ 2010 13400   730    38     9]]
75
[2007  980  590   12    1]


In [84]:
# Question 15: Advanced Array Operations
# Q15.1: Apply a function to calculate 5% interest on all account balances
def intrest_function(x):
    return x*1.05
hlo =intrest_function(banking_data[:,1])
print(hlo) 

# Q15.2: Use np.where to categorize customers by balance ranges
categorize = np.where(banking_data[:,1]>10000 , "High" , "low")
print(categorize)

# Q15.3: Use np.select to categorize customers by credit score ranges
ranges= [
    (banking_data[:,2]<500),
    (banking_data[:,2]>=500) & (banking_data[:,2]<=800),
    (banking_data[:,2]>800)
]
categories = ['Low Score', 'Mid Score' , 'High Score']
customers_ranges =np.select(ranges,categories,default='Unkown')
print(customers_ranges) 


# Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_balance(x): return x * 0.8 #20% discount
def mid_balance(x): return x * 0.85 #15% discount
def high_balance(x):return x * 0.9 #10% discount
discounted_price = np.piecewise(
    banking_data[:,1],
    [banking_data[:,1]<7000,(banking_data[:,1]>=7000)&banking_data[:,1]<=14000,banking_data[:,1]>14000],
    [low_balance,mid_balance,high_balance]
)
print(discounted_price)

# Q15.5: Use np.apply_along_axis to calculate the sum of each row
rows_sum = np.apply_along_axis(np.sum,1,banking_data)
print(rows_sum)


[15991.5  8872.5 24150.   1312.5 18784.5  5670.   1029.  22102.5  7035.
 14070. ]
['High' 'low' 'High' 'low' 'High' 'low' 'low' 'High' 'low' 'High']
['Mid Score' 'Mid Score' 'Mid Score' 'Mid Score' 'Mid Score' 'Mid Score'
 'Mid Score' 'High Score' 'Mid Score' 'Mid Score']
[13707  7182 20700  1062 16101  4590   833 18945  5695 11390]
[17994 11159 25853  3881 20695  8100  3590 23938  9446 16187]


In [95]:
# Question 16: Array Concatenation and Stacking
# Q16.1: Concatenate two arrays horizontally using np.hstack()
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
horizontal_stack = np.hstack([arr1,arr2])
print(horizontal_stack)
# Q16.2: Concatenate two arrays vertically using np.vstack()
vertical_stack = np.vstack([arr1,arr2])
print(vertical_stack)
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
concatination = np.concatenate([arr2,arr2],axis=0)
print(concatination)

# Q16.4: Stack arrays depth-wise using np.dstack()
depth_stacked = np.dstack([arr1,arr2])
print(depth_stacked)

# Q16.5: Create a column stack using np.column_stack()

column_stacked = np.column_stack([arr1,arr2])
print(column_stacked)

[1 2 3 1 2 3]
[[1 2 3]
 [1 2 3]]
[1 2 3 1 2 3]
[[[1 1]
  [2 2]
  [3 3]]]
[[1 1]
 [2 2]
 [3 3]]


In [112]:
# Question 17: Array Splitting Operations
# Q17.1: Split an array into 3 equal parts using np.split()
arr_to_split = np.array([1,2,3,4,5,6,7,8,9])
splitted_array = np.split(arr_to_split,3)
print(splitted_array)
# Q17.2: Split an array at specific indices using np.split()
arr_to_split = np.array([1,2,3,4,5,6,7,8,9,10])
split_at_indices = np.split(arr_to_split,[3,6])
print(split_at_indices)

# Q17.3: Split an array horizontally using np.hsplit()
arr_2d = np.array([[1,2,3],[4,5,6]])
split_hori = np.hsplit(arr_2d,3)
print(split_hori)

# Q17.4: Split an array vertically using np.vsplit()
split_veti = np.vsplit(arr_2d,2)
print(split_veti)


# Q17.5: Split an array into equal chunks using np.array_split()
chunks = np.array_split(arr_2d,3)
print(chunks)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [ ]:
# Question 18: Array Repetition and Tiling
# Q18.1: Repeat each element of an array 3 times using np.repeat()
arr1 = np.array([1,2])
repeat_arr = np.repeat(arr1,3)
print(repeat_arr)
print()
# Q18.2: Repeat an entire array 2 times using np.tile()
repeat_entire_arr = np.tile(arr1,2)
print(repeat_entire_arr)
print()
print("rows x cloumns")
repeat_entire_arr = np.tile(arr1,(2,4))x
print(repeat_entire_arr)

repeat_entire_arr = np.tile(arr1,2)
print(repeat_entire_arr)
print()
# Q18.3: Repeat a 2D array using np.tile()
arr_2d = np.array([[1,2,3],[4,5,6]])
repeat_2d_arr = np.tile(arr_2d,3)
print(repeat_2d_arr)
# Q18.4: Create a pattern using np.tile()
print()
pattern= np.tile(arr1,(3,4))
print(pattern)
print()
# Q18.5: Repeat elements with different counts using np.repeat()
arr5 = np.array([1,2,3,4])
repeat_count = [2,1,3,5]
diff_counts = np.repeat(arr5,repeat_count)
print(diff_counts)

[1 1 1 2 2 2]

[1 2 1 2]

rows x cloumns
[[1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2]]
[1 2 1 2]

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]

[[1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2]
 [1 2 1 2 1 2 1 2]]

[1 1 2 3 3 3 4 4 4 4 4]


In [ ]:
# Question 19: Array Comparison and Logical Operations
# Q19.1: Compare two arrays for equality using np.array_equal()
arr1= np.array([1,2,3])
arr2= np.array([1,2,4])
arr3= np.array([1,2,3])
equal = np.array_equal(arr1,arr3)
print(equal)
print()
# Q19.2: Check if arrays are close using np.allclose()
arr_4 = np.array([1.0, 2.0, 3.0])
arr_5 = np.array([1.001, 2.001, 3.001])
close = np.allclose(arr_4,arr_5,atol=0.01)
print(close)
print()
# Q19.3: Apply logical AND operation between arrays
logical_and = np.logical_and(arr1>1,arr1<4)
print(logical_and)
print()

# Q19.4: Apply logical OR operation between arrays
logical_or = np.logical_or(arr1==1,arr1==3)
print(logical_or)
print()

# Q19.5: Apply logical NOT operation to an array
logical_not = np.logical_not(arr1==1)
print(logical_not)
print()


True

True

[False  True  True]

[ True False  True]

[False  True  True]



In [165]:
# Question 20: Array Set Operations
# Q20.1: Find unique elements in an array using np.unique()
arr_1 = np.array([1,1,2,3,4,5,6,7,8,1,2,3,4,5,6,3,2,2,1,4,1,5,7,0])
unique = np.unique(arr_1)
print(unique)

# Q20.2: Find the intersection of two arrays using np.intersect1d()
arr1= np.array([1,2,3])
arr2= np.array([1,2,4])
intersection = np.intersect1d(arr1,arr2)
print(intersection)


# Q20.3: Find the union of two arrays using np.union1d()
union = np.union1d(arr1,arr2)
print(union)

# Q20.4: Find elements in first array but not in second using np.setdiff1d()
diff = np.setdiff1d(arr1,arr2)
print(diff)


# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
symmetric = np.setxor1d(arr1,arr2)
print(symmetric)

[0 1 2 3 4 5 6 7 8]
[1 2]
[1 2 3 4]
[3]
[3 4]
